apiVersion: v1
kind: Service
metadata:
  name: memory-profiler-service
spec:
  type: NodePort
  selector:
    app: memory-profiler
  ports:
    - port: 17832
      protocol: TCP
      name: profiler
    - port: 3000
      protocol: TCP
      name: node-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: memory-profiler
  name: memory-profiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-profiler
  template:
    metadata:
      labels:
        app: memory-profiler
    spec:
      containers:
        - name: openmina
          image: vladsimplestakingcom/openmina:keep-frame-pointers
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - name: node
              containerPort: 8302
              protocol: TCP
            - name: profiler
              containerPort: 17832
              protocol: TCP
            - name: node-server
              containerPort: 3000
              protocol: TCP
          env:
            - name: BPF_MEM
              value: "1"
            - name: RUST_LOG
              value: "info"
          resources:
            requests:
              memory: 16G
            limits:
              memory: 32G
          volumeMounts:
            - mountPath: /sys/kernel/debug
              name: sys-kernel-debug
            - mountPath: /proc
              name: proc
      volumes:
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: proc
          hostPath:
            path: /proc
---
